import React from "react";
import { Inter } from "next/font/google";
import "../../../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Reset Password | HelpTix",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${inter.className} flex h-full items-center py-16 bg-gray-50`}
      >
        {children}
      </body>
    </html>
  );
}
