import { Inter } from "next/font/google";
import "../../../globals.css";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Reset Password",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${inter.className} flex h-full items-center py-16 bg-gray-50`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
