import { Inter } from "next/font/google";
import "../../globals.css";
import Footer from "./components/Footer";
import Navbar from "@/app/(pages)/(landing-page)/components/Navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CRM Prototype",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="">
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
